export {default as PropColor }  from './src/PropColor.vue'
export {default as PropTextarea}  from './src/PropTextarea.vue'
export {default as propNumber}  from './src/PropNumber.vue'
export {default as propSelect}  from './src/PropSelect.vue'
export {default as PropFontGroup}  from './src/PropFontGroup.vue'
export {default as PropUpload}  from './src/PropUpload.vue'
export {default as PropSlider}  from './src/PropSlider.vue'
export {default as PropPaddingGroup}  from './src/PropPaddingGroup.vue'
export {default as PropBoxShadow}  from './src/PropBoxShadow.vue'
export {default as PropCheckbox}  from './src/PropCheck.vue'
export {default as PropBorderGroup}  from './src/PropBorderGroup.vue'
export {default as PropBackgroundImg}  from './src/PropBackgroundImg.vue'
export {default as PropInput}  from './src/PropInput'
export {default as PropEditor}  from './src/PropEditor.vue'
